<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreNoteRequest extends FormRequest
{
    protected function failedValidation(Validator $validator)
    {
//        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' =>       ['required', 'string', 'max:255'],
            'description' => ['nullable', 'string'],
            'category_id' => [
                            'required',
                            'numeric',
                            Rule::exists('categories', 'id')
                                ->where('user_id', request()->user()->id),
            ],
            'due_date' =>    ['nullable', 'date_format:Y-m-d H:i:s']
        ];
    }

    public function getValidator(): Validator
    {
        return $this->validator;
    }
}
